# Generated by Django 5.2.8 on 2025-11-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
