# Generated by Django 5.2.8 on 2025-11-27 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_sitevisitor'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sitevisitor',
            new_name='site_visito_ip_addr_da66ac_idx',
            old_name='site_visito_ip_addr_idx',
        ),
    ]
