# Generated by Django 5.2.8 on 2025-12-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_promoted',
            field=models.BooleanField(default=False, help_text='Mark this shop as promoted to show in homepage carousel'),
        ),
        migrations.AddField(
            model_name='shop',
            name='promoted_at',
            field=models.DateTimeField(blank=True, help_text='When this shop was promoted', null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='promotion_priority',
            field=models.IntegerField(default=0, help_text='Higher priority shops appear first in carousel (0-100)'),
        ),
    ]
