# Generated by Django 5.2.8 on 2025-12-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_coupon_order_coupon_code_order_coupon_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
