# Generated by Django 5.2.8 on 2025-12-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_mrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
